sudo: required
services:
  - docker

env:
  global:
    - REPO=steadyserv/node
  matrix:
    - VERSION=8.2-alpine TAG=alpine TAG=latest MAJOR=8
    - VERSION=8.1-alpine
    - VERSION=8.0-alpine
    - VERSION=7.6-alpine MAJOR=7
    - VERSION=7.1-alpine
    - VERSION=7.1
    - VERSION=7.0
    - VERSION=6.5 MAJOR=6
    - VERSION=6.4
    - VERSION=6.3
    - VERSION=6.0
    - VERSION=5.8 MAJOR=5
    - VERSION=0.10 MAJOR=0.10

before_script:
  - env | sort
  - cd "$VERSION"
  - export IMAGE="${REPO}:${VERSION}"

script: ../.travis/build.sh
