sudo: required
services:
  - docker

env:
  global:
    - REPO=steadyserv/node
  matrix:
    # always prefer latest tag on most recent *alpine* distribution (TAG=latest)
    - VERSION=12.0 DIST=alpine TAG=latest
    - VERSION=12.0 DIST=slim
    - VERSION=10.15 DIST=alpine TAG=lts-alpine
    - VERSION=10.15 DIST=slim TAG=lts-slim
    - VERSION=9.11 DIST=alpine
    - VERSION=9.11 DIST=slim
    - VERSION=8.16 DIST=alpine
    - VERSION=8.16 DIST=slim
before_script:
  - env | sort

script: ./.travis/build.sh
