sudo: required
services:
  - docker

env:
  global:
    - REPO=steadyserv/node
  matrix:
    - VERSION=6.5 MAJOR=6 TAG=latest
    - VERSION=6.4
    - VERSION=6.3
    - VERSION=6.0
    - VERSION=5.8 MAJOR=5
    - VERSION=0.10 MAJOR=0.10

before_script:
  - env | sort
  - cd "$VERSION"
  - export IMAGE="${REPO}:${VERSION}"

script: ../.travis/build.sh
